import type { ContentTemplate, ContentElementTemplate } from "@/types/layout"

export const CONTENT_TEMPLATES: Record<string, ContentTemplate> = {
  "magazine-cover": {
    type: "magazine-cover",
    name: "Magazine Cover",
    description: "Eye-catching cover with title, hero image, and publication info",
    requiredElements: [
      {
        role: "title",
        type: "text",
        required: true,
        defaultSize: { width: 4, height: 1 },
        placement: "top",
        priority: 10,
        textStyle: "headline",
      },
      {
        role: "subtitle",
        type: "text",
        required: false,
        defaultSize: { width: 3, height: 1 },
        placement: "top",
        priority: 8,
        textStyle: "subhead",
      },
      {
        role: "hero-image",
        type: "image",
        required: true,
        defaultSize: { width: 6, height: 5 },
        placement: "center",
        priority: 9,
      },
      {
        role: "issue-info",
        type: "text",
        required: true,
        defaultSize: { width: 2, height: 1 },
        placement: "top",
        priority: 6,
        textStyle: "caption",
      },
      {
        role: "barcode",
        type: "image",
        required: true,
        defaultSize: { width: 1, height: 1 },
        placement: "bottom",
        priority: 5,
      },
    ],
    layoutPriorities: ["visual-impact", "hierarchy", "brand-consistency"],
    aestheticRules: ["golden-ratio", "rule-of-thirds"],
  },

  "table-of-contents": {
    type: "table-of-contents",
    name: "Table of Contents",
    description: "Organized content listing with page numbers and sections",
    requiredElements: [
      {
        role: "title",
        type: "text",
        required: true,
        defaultSize: { width: 6, height: 1 },
        placement: "top",
        priority: 10,
        textStyle: "headline",
      },
      {
        role: "body-text",
        type: "text",
        required: true,
        defaultSize: { width: 3, height: 6 },
        placement: "left",
        priority: 9,
        textStyle: "body",
      },
      {
        role: "hero-image",
        type: "image",
        required: false,
        defaultSize: { width: 3, height: 4 },
        placement: "right",
        priority: 7,
      },
      {
        role: "page-number",
        type: "text",
        required: true,
        defaultSize: { width: 1, height: 1 },
        placement: "bottom",
        priority: 5,
        textStyle: "caption",
      },
    ],
    layoutPriorities: ["readability", "organization", "navigation"],
    aestheticRules: ["uniform", "modular"],
  },

  "feature-spread": {
    type: "feature-spread",
    name: "Feature Spread",
    description: "Editorial spread with large visuals and flowing text",
    requiredElements: [
      {
        role: "title",
        type: "text",
        required: true,
        defaultSize: { width: 4, height: 1 },
        placement: "top",
        priority: 10,
        textStyle: "headline",
      },
      {
        role: "subtitle",
        type: "text",
        required: false,
        defaultSize: { width: 3, height: 1 },
        placement: "top",
        priority: 8,
        textStyle: "subhead",
      },
      {
        role: "hero-image",
        type: "image",
        required: true,
        defaultSize: { width: 8, height: 4 },
        placement: "center",
        priority: 9,
      },
      {
        role: "body-text",
        type: "text",
        required: true,
        defaultSize: { width: 4, height: 3 },
        placement: "flexible",
        priority: 7,
        textStyle: "body",
      },
      {
        role: "pull-quote",
        type: "text",
        required: false,
        defaultSize: { width: 2, height: 2 },
        placement: "flexible",
        priority: 6,
        textStyle: "quote",
      },
      {
        role: "byline",
        type: "text",
        required: true,
        defaultSize: { width: 2, height: 1 },
        placement: "bottom",
        priority: 5,
        textStyle: "byline",
      },
    ],
    layoutPriorities: ["visual-flow", "readability", "dramatic-impact"],
    aestheticRules: ["golden-ratio", "fibonacci"],
  },

  "interview-page": {
    type: "interview-page",
    name: "Interview Page",
    description: "Q&A format with portrait and conversational layout",
    requiredElements: [
      {
        role: "title",
        type: "text",
        required: true,
        defaultSize: { width: 4, height: 1 },
        placement: "top",
        priority: 10,
        textStyle: "headline",
      },
      {
        role: "portrait",
        type: "image",
        required: true,
        defaultSize: { width: 2, height: 3 },
        placement: "left",
        priority: 9,
      },
      {
        role: "question",
        type: "text",
        required: true,
        defaultSize: { width: 4, height: 1 },
        placement: "flexible",
        priority: 8,
        textStyle: "subhead",
      },
      {
        role: "answer",
        type: "text",
        required: true,
        defaultSize: { width: 4, height: 2 },
        placement: "flexible",
        priority: 7,
        textStyle: "body",
      },
      {
        role: "pull-quote",
        type: "text",
        required: false,
        defaultSize: { width: 3, height: 2 },
        placement: "right",
        priority: 6,
        textStyle: "quote",
      },
    ],
    layoutPriorities: ["conversation-flow", "personality", "readability"],
    aestheticRules: ["modular", "uniform"],
  },

  "product-showcase": {
    type: "product-showcase",
    name: "Product Showcase",
    description: "Product-focused layout with clear callouts and specifications",
    requiredElements: [
      {
        role: "title",
        type: "text",
        required: true,
        defaultSize: { width: 4, height: 1 },
        placement: "top",
        priority: 10,
        textStyle: "headline",
      },
      {
        role: "product-image",
        type: "image",
        required: true,
        defaultSize: { width: 4, height: 4 },
        placement: "left",
        priority: 9,
      },
      {
        role: "product-specs",
        type: "text",
        required: true,
        defaultSize: { width: 2, height: 3 },
        placement: "right",
        priority: 8,
        textStyle: "body",
      },
      {
        role: "price",
        type: "text",
        required: true,
        defaultSize: { width: 2, height: 1 },
        placement: "right",
        priority: 7,
        textStyle: "headline",
      },
      {
        role: "call-to-action",
        type: "text",
        required: true,
        defaultSize: { width: 2, height: 1 },
        placement: "bottom",
        priority: 6,
        textStyle: "subhead",
      },
    ],
    layoutPriorities: ["product-focus", "clear-information", "conversion"],
    aestheticRules: ["rule-of-thirds", "uniform"],
  },

  "photo-essay": {
    type: "photo-essay",
    name: "Photo Essay",
    description: "Image-heavy layout with minimal text and strong visual narrative",
    requiredElements: [
      {
        role: "title",
        type: "text",
        required: true,
        defaultSize: { width: 3, height: 1 },
        placement: "top",
        priority: 10,
        textStyle: "headline",
      },
      {
        role: "hero-image",
        type: "image",
        required: true,
        defaultSize: { width: 6, height: 4 },
        placement: "center",
        priority: 9,
      },
      {
        role: "hero-image",
        type: "image",
        required: true,
        defaultSize: { width: 3, height: 3 },
        placement: "flexible",
        priority: 8,
      },
      {
        role: "hero-image",
        type: "image",
        required: true,
        defaultSize: { width: 2, height: 2 },
        placement: "flexible",
        priority: 7,
      },
      {
        role: "caption",
        type: "text",
        required: false,
        defaultSize: { width: 2, height: 1 },
        placement: "bottom",
        priority: 6,
        textStyle: "caption",
      },
    ],
    layoutPriorities: ["visual-storytelling", "image-quality", "minimal-text"],
    aestheticRules: ["fibonacci", "golden-ratio"],
  },
}

export function getContentTemplate(type: string): ContentTemplate | null {
  return CONTENT_TEMPLATES[type] || null
}

export function getRequiredElementsForType(type: string): ContentElementTemplate[] {
  const template = getContentTemplate(type)
  return template ? template.requiredElements.filter((el) => el.required) : []
}

export function getAllElementsForType(type: string): ContentElementTemplate[] {
  const template = getContentTemplate(type)
  return template ? template.requiredElements : []
}
